# Generated by Django 5.2.8 on 2026-05-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('reading_completed', 'Reading completed'), ('quiz_answer', 'Quiz answer'), ('quiz_bonus', 'Quiz bonus'), ('reread', 'Reread'), ('achievement', 'Achievement'), ('avatar_purchase', 'Avatar purchase'), ('adjustment', 'Adjustment')], max_length=40),
        ),
    ]
