# Generated by Django 5.2.8 on 2026-05-05 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_price_paid', models.PositiveIntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='avataroption',
            options={'ordering': ['layer_order', 'option_type', 'coin_price', 'name']},
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='base_style',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='hair_style',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='skin_tone',
        ),
        migrations.AddField(
            model_name='avataroption',
            name='layer_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='accessories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'option_type': 'accessory'}, related_name='accessory_users', to='accounts.avataroption'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='base_body',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'base_body'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_body_users', to='accounts.avataroption'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='eyes',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'eyes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyes_users', to='accounts.avataroption'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='hair_style',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'hair_style'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hair_style_users', to='accounts.avataroption'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='outfit',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'outfit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_users', to='accounts.avataroption'),
        ),
        migrations.AlterField(
            model_name='avataroption',
            name='option_type',
            field=models.CharField(choices=[('preset', 'Preset'), ('base_body', 'Base body'), ('hair_style', 'Hair style'), ('eyes', 'Eyes'), ('accessory', 'Accessory'), ('outfit', 'Outfit')], default='preset', max_length=20),
        ),
        migrations.AddIndex(
            model_name='avataroption',
            index=models.Index(fields=['option_type', 'is_active'], name='accounts_av_option__52ade2_idx'),
        ),
        migrations.AddField(
            model_name='useravatarunlock',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='accounts.avataroption'),
        ),
        migrations.AddField(
            model_name='useravatarunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useravatarunlock',
            unique_together={('user', 'option')},
        ),
    ]
