# Generated by Django 5.2.8 on 2026-05-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useravatarunlock_alter_avataroption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='body_style',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_type': 'body_style'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_style_users', to='accounts.avataroption'),
        ),
        migrations.AlterField(
            model_name='avataroption',
            name='option_type',
            field=models.CharField(choices=[('preset', 'Preset'), ('base_body', 'Base body'), ('body_style', 'Body style'), ('hair_style', 'Hair style'), ('eyes', 'Eyes'), ('accessory', 'Accessory'), ('outfit', 'Outfit')], default='preset', max_length=20),
        ),
    ]
