# Generated by Django 5.2.8 on 2026-05-06 20:21

import django.db.models.deletion
from django.db import migrations, models


def seed_avatar_category_requirements(apps, schema_editor):
    AvatarOption = apps.get_model("accounts", "AvatarOption")
    Category = apps.get_model("reading", "Category")
    requirements = {
        "Base dourada Lecto": ("cotidiano", 10),
        "Lenco violeta": ("cultura-pop", 10),
        "Cachecol dourado": ("viagens", 10),
        "Fones azul": ("tecnologia", 10),
        "Gorro academico": ("cotidiano", 10),
        "Livro lateral": ("contos", 10),
    }

    for option_name, (category_slug, required_reads) in requirements.items():
        category = Category.objects.filter(slug=category_slug).first()
        if not category:
            continue
        AvatarOption.objects.filter(name=option_name).update(
            required_category=category,
            required_category_reads=required_reads,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useravatar_body_style_alter_avataroption_option_type'),
        ('reading', '0002_text_image_canvas_height_text_image_canvas_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataroption',
            name='required_category',
            field=models.ForeignKey(blank=True, help_text='Categoria que precisa ser lida para liberar este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_options', to='reading.category'),
        ),
        migrations.AddField(
            model_name='avataroption',
            name='required_category_reads',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantidade de textos concluidos na categoria exigida para compra.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_reading_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_avatar_category_requirements, migrations.RunPython.noop),
    ]
