# Generated by Django 5.2.8 on 2026-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('animation', 'Animation'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='assets/')),
                ('external_url', models.URLField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('attribution', models.CharField(blank=True, max_length=200)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
