# Generated by Django 5.2.8 on 2026-05-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description_pt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('publisher', models.CharField(choices=[('marvel', 'Marvel'), ('dc', 'DC'), ('other', 'Other')], max_length=20)),
                ('description_pt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('description_pt', models.TextField(blank=True)),
                ('min_words', models.PositiveSmallIntegerField(default=40)),
                ('max_words', models.PositiveSmallIntegerField(default=80)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary_pt', models.TextField()),
                ('content_en', models.TextField()),
                ('cover_image', models.FileField(blank=True, upload_to='texts/covers/')),
                ('animation_asset', models.FileField(blank=True, upload_to='texts/animations/')),
                ('image_prompt', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('estimated_reading_time', models.PositiveSmallIntegerField(default=1)),
                ('is_premium', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='reading.category')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='reading.character')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='reading.level')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=80)),
                ('translation_pt', models.CharField(max_length=160)),
                ('pronunciation_pt', models.CharField(max_length=120)),
                ('ipa', models.CharField(blank=True, max_length=120)),
                ('audio_url', models.URLField(blank=True)),
                ('tts_provider', models.CharField(blank=True, max_length=80)),
                ('example_en', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='reading.text')),
            ],
            options={
                'ordering': ['order', 'word_en'],
                'unique_together': {('text', 'word_en')},
            },
        ),
    ]
