# Generated by Django 5.2.8 on 2026-05-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='image_canvas_height',
            field=models.PositiveSmallIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='text',
            name='image_canvas_width',
            field=models.PositiveSmallIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='frequency_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='lemma_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective')], max_length=20),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('dynamic_nlp', 'Dynamic NLP'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['part_of_speech', 'source'], name='reading_voc_part_of_f40442_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['lemma_en'], name='reading_voc_lemma_e_18d103_idx'),
        ),
    ]
